server:
  port: 8082

spring:
  application:
    name: microservicio-ventas

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.45.19.226:3306/bdclientes
    username: admin
    password: adminpass

  jpa:
    hibernate:
      ddl-auto: update # Crea/actualiza las tablas automáticamente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

microservicio:
  inventario:
    url: ${URI_INVENTARIO:http://localhost:8081}

security: 
  jwt:
    secret: EstaEsUnaClaveSuperSecretaYLoSuficientementeLargaParaQueSpringNoSeQueje2025
    expiration: 3600000